---
title: "Linked map"
description: |
  A short description of the post.
author:
  - name: Dr. KAM Tin Seong, <br>Associate Professor of Information Systems (Practice)
    url: https://www.smu.edu.sg/faculty/profile/9618/KAM-Tin-Seong
date: 05-27-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
packages = c('tidycensus', 'ggiraph', 'tidyverse', 'patchwork')
for (p in packages){
if(!require(p, character.only = T)){
install.packages(p)
}
library(p,character.only = T)
}
```


```{r}
vt_income <- get_acs(
  geography = "county",
  variables = "B19013_001",
  state = "VT",
  year = 2019,
  geometry = TRUE
) %>%
  mutate(NAME = str_remove(NAME, " County, Vermont"))
```

```{r}
vt_map <- ggplot(vt_income, 
                 aes(fill = estimate)) + 
  geom_sf_interactive(aes(data_id = GEOID)) + 
  scale_fill_distiller(palette = "Greens",
                       direction = 1, 
                       guide = FALSE) + 
  theme_void()
```

```{r}
vt_plot <- ggplot(vt_income, 
                  aes(x = estimate, 
                      y = reorder(NAME, estimate), 
                                 fill = estimate)) +
  geom_errorbarh(aes(xmin = estimate - moe, 
                     xmax = estimate + moe)) +
  geom_point_interactive(color = "black", 
                         size = 4, 
                         shape = 21,
                         aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "Greens", 
                       direction = 1,
                       labels = scales::dollar) + 
  labs(title = "Household income by county in Vermont",
       subtitle = "2015-2019 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)",
       fill = "ACS estimate") + 
  theme_minimal()
```

```{r}
girafe(ggobj = vt_map + vt_plot, 
       width_svg = 10, 
       height_svg = 4) %>%
  girafe_options(opts_hover(css = "fill:cyan;"))
```

